import os
import datetime
import random
from github import Github
from github import Auth
from google import genai
from google.genai import types

def generate_coding_problem(api_key):
    """Generates a random Python or JS coding problem using Gemini."""
    if not api_key:
        raise ValueError("GEMINI_API_KEY is missing.")
        
    client = genai.Client(api_key=api_key)
    
    language = random.choice(["Python", "JavaScript"])
    difficulty = random.choice(["Easy", "Medium", "Hard"])
    
    prompt = f"""
    You are an expert software engineering interviewer. 
    Create a unique, interesting {difficulty} level LeetCode-style coding problem to be solved in {language}.
    
    Format the response strictly in Markdown:
    # Problem Title
    
    ## Description
    (problem description)
    
    ## Examples
    (2-3 examples with input/output)
    
    ## Solution ({language})
    ```{'python' if language == 'Python' else 'javascript'}
    // write the optimal solution here
    ```
    
    ## Complexity
    Time: O(?)
    Space: O(?)
    """
    
    response = client.models.generate_content(
        model='gemini-3.1-flash-lite',
        contents=prompt,
    )
    
    title_line = response.text.split('\n')[0]
    safe_title = title_line.replace('#', '').strip().replace(' ', '-').lower()
    
    return language, safe_title, response.text

def run_github_bot(api_key=None, github_pat=None, callback=print):
    """Main execution block for the GitHub Bot."""
    callback("Starting GitHub Automation Bot...")
    pat = github_pat or os.environ.get("GITHUB_PAT")
    
    if not pat:
        callback("GITHUB_PAT not found. Skipping GitHub automation.")
        return
        
    try:
        # Authenticate
        callback("Authenticating with GitHub...")
        auth = Auth.Token(pat)
        g = Github(auth=auth)
        user = g.get_user()
        
        repo_name = "daily-coding-problems"
        
        # Get or create repository
        try:
            repo = user.get_repo(repo_name)
            callback(f"Found repository: {repo.full_name}")
        except Exception:
            callback(f"Creating repository: {repo_name}")
            repo = user.create_repo(
                repo_name, 
                description="Daily automated coding problems generated by AI.",
                private=False,
                auto_init=True
            )
            
        # Generate problem
        callback("Generating coding problem via Gemini...")
        language, safe_title, content = generate_coding_problem(api_key)
        
        # Create folder and file
        date_str = datetime.datetime.now().strftime("%Y-%m-%d")
        folder_path = f"problems/{date_str}"
        
        try:
            contents = repo.get_contents(folder_path)
            problem_num = len(contents) + 1 if isinstance(contents, list) else 1
        except Exception:
            problem_num = 1
            
        file_name = f"Problem-{problem_num}-of-{language}.md"
        file_path = f"{folder_path}/{file_name}"
        
        callback(f"Pushing to GitHub: {file_path}")
        repo.create_file(
            path=file_path,
            message=f"Add daily problem: {safe_title}",
            content=content,
            branch="main"
        )
        callback("Successfully pushed to GitHub!")
        return f"https://github.com/{repo.full_name}/blob/main/{file_path}"
        
    except Exception as e:
        callback(f"GitHub Bot Error: {e}")
        raise e

if __name__ == "__main__":
    run_github_bot()
